### ISSUE TITLE
UnsatisfiedLinkError /lib/arm/libti.mely.so: has text relocations

### ISSUE THREAD

**Issue by SudoPlz** [benbahrenburg/ti.mely#11]
I get those errors when trying to run my app with Titanium sdk 5.2.1

	[ERROR] :  linker: /data/app/gr.elabs.mellon-1/lib/arm/libti.mely.so: has text relocations
	[ERROR] :  TiApplication: (KrollRuntimeThread) [82,264] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/gr.elabs.mellon-1/lib/arm/libti.mely.so: has text relocations; Titanium 5.2.1,2016/03/18 22:51,23e1c7d
	[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/gr.elabs.mellon-1/lib/arm/libti.mely.so: has text relocations
	[ERROR] :  TiApplication: 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
	[ERROR] :  TiApplication: 	at java.lang.System.loadLibrary(System.java:1076)
	[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
	[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
	[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
	[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
	[WARN] :   TiTempFileHelper: (main) [117,381] The external temp directory doesn't exist, skipping cleanup

**Comment by SudoPlz** [comment]
By using the above pull request and compiling with Titanium sdk v5.2.1 I never saw the error again. Thanks Konstantin.
